from pydantic import BaseModel, Field
from typing import List, Optional, Dict, Any

# Analysis Schemas
class AnalyzeRequest(BaseModel):
    cv_text: str = Field(..., description="The full text of the user's CV", example="I am a software engineer with 5 years experience...")
    job_text: str = Field(..., description="The full text of the job description", example="We need a Python backend developer...")
    user_id: Optional[str] = Field("default-user-id", description="Optional user ID for tracking history")

class AnalyzeResponse(BaseModel):
    analysis_id: str = Field(..., description="The unique ID of the saved analysis")
    match_score: int = Field(..., description="The calculated match score (0-100)")
    summary: str = Field(..., description="Executive summary generated by AI")
    report: str = Field(..., description="Full Markdown report")
    
# Interview Schemas
class GenerateQuestionsRequest(BaseModel):
    analysis_id: str = Field(..., description="The ID of the analysis to generate questions for")

class QuestionItem(BaseModel):
    id: int
    question: str
    focus_area: str
    question_type: str

class GenerateQuestionsResponse(BaseModel):
    questions: List[QuestionItem]

class EvaluateInterviewRequest(BaseModel):
    analysis_id: str
    user_id: Optional[str] = "default-user-id"
    questions: List[Dict[str, Any]]
    answers: Dict[str, str] = Field(..., description="Dictionary mapping question IDs (as string) to user answers")

class PerQuestionFeedback(BaseModel):
    question_id: int
    score: int
    feedback: str

class EvaluateInterviewResponse(BaseModel):
    overall_score: int
    per_question_feedback: List[PerQuestionFeedback]
    strengths: List[str]
    areas_to_improve: List[str]

# History Schemas
class HistoryItemResponse(BaseModel):
    id: str
    match_score: int
    summary: str
    created_at: str

class DeleteHistoryResponse(BaseModel):
    status: str
    deleted_id: str

# Export Schemas
class ExportRequest(BaseModel):
    analysis_id: str

class ExportMarkdownResponse(BaseModel):
    markdown: str
